# SEO Values
title: html2md
tagline: Simple and fast HTML to Markdown converter
description: Simple and fast HTML to Markdown converter with table support
url: https://dracula.github.io/gh-pages/

# GitHub Values
github:
  owner_name: Tim Gromeyer
  owner_url: https://github.com/software-made-easy
  repository_url: https://github.com/dracula/gh-pages

show_header: false
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
